---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-rbac
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: keycloak-platform
    component: tenant
spec:
  project: default
  source:
    repoURL: https://github.com/rhpds/ocp-cluster-addons.git
    targetRevision: keycloak-wip
    path: keycloak/tenant/charts/tenant-rbac
    helm:
      values: |
        deployer:
          guid: default
        users:
          mode: generate
          generate:
            count: 5
            prefix: user
            startNumber: 1
        namespaces:
          mode: generate
          generate:
            count: 5
            prefix: user
            suffix: -project
            startNumber: 1
        rbac:
          namespaceAdmin:
            enabled: true
            clusterRole: admin
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
