---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-namespaces
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: keycloak-platform
    component: tenant
spec:
  project: default
  source:
    repoURL: https://github.com/rhpds/ocp-cluster-addons.git
    targetRevision: keycloak-wip
    path: keycloak/tenant/charts/tenant-namespaces
    helm:
      values: |
        deployer:
          guid: default
        namespaces:
          mode: generate
          generate:
            count: 5
            prefix: user
            suffix: -project
            startNumber: 1
        resourceQuota:
          enabled: true
        limitRange:
          enabled: true
        networkPolicy:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
