---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: compliance
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: this
    targetRevision: main
    path: compliance
    helm:
      values: |
        operator:
          namespace: openshift-compliance
          startingCSV: compliance-operator.x.y.z
          installPlanApproval: Manual
          config:
            nodeSelector:
              node-role.kubernetes.io/worker: ""
              env:
              - name: PLATFORM
                value: "HyperShift"
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-compliance
