---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-tenants
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: keycloak-platform
    component: tenant
spec:
  project: default
  source:
    repoURL: https://github.com/rhpds/ocp-cluster-addons.git
    targetRevision: keycloak-wip
    path: keycloak/tenant
    helm:
      values: |
        deployer:
          guid: default
        keycloak:
          namespace: keycloak
          realmName: sso
        users:
          mode: generate
          generate:
            count: 5
            prefix: user
            startNumber: 1
          password: changeme123
        namespaces:
          mode: generate
          generate:
            count: 5
            prefix: user
            suffix: -project
            startNumber: 1
        resourceQuota:
          enabled: true
        limitRange:
          enabled: true
        networkPolicy:
          enabled: false
        rbac:
          namespaceAdmin:
            enabled: true
            clusterRole: admin
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
