---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-tenants
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: keycloak-platform
    component: tenant
spec:
  project: default
  source:
    repoURL: ${GIT_REPO}
    targetRevision: ${GIT_BRANCH}
    path: keycloak/tenant
    helm:
      values: |
        deployer:
          guid: ${GUID}
        keycloak:
          namespace: keycloak
          realmName: sso
        users:
          mode: generate
          generate:
            count: ${USER_COUNT}
            prefix: ${USER_PREFIX}
            startNumber: 1
          password: ${USER_PASSWORD}
        namespaces:
          mode: generate
          generate:
            count: ${USER_COUNT}
            prefix: ${USER_PREFIX}
            suffix: -project
            startNumber: 1
        resourceQuota:
          enabled: true
        limitRange:
          enabled: true
        networkPolicy:
          enabled: false
        rbac:
          namespaceAdmin:
            enabled: true
            clusterRole: admin
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
