---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-tenants
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: keycloak-platform
    component: tenant
spec:
  project: default
  source:
    repoURL: https://github.com/rhpds/ocp-cluster-addons.git
    targetRevision: keycloak-wip
    path: keycloak/tenant/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
