{{- if and .Values.dscinitialization .Values.dscinitialization.serviceMesh -}}
---
apiVersion: {{ .Values.operator.apiVersion }}
kind: DSCInitialization
metadata:
  name: {{ .Values.dscinitialization.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  serviceMesh:
    {{- .Values.dscinitialization.serviceMesh | toYaml | nindent 4 }}
{{- end }}
