---
# RBAC for ArgoCD to manage Keycloak resources
# Apply this before deploying the Keycloak applications

# ClusterRole with permissions needed for Keycloak deployment
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-keycloak-manager
  labels:
    app.kubernetes.io/part-of: keycloak-platform
rules:
  # Keycloak CRDs
  - apiGroups:
      - k8s.keycloak.org
    resources:
      - keycloaks
      - keycloakrealmimports
      - keycloakusers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Core resources
  - apiGroups:
      - ""
    resources:
      - namespaces
      - secrets
      - configmaps
      - services
      - serviceaccounts
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Apps resources
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # RBAC resources
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Route resources (OpenShift)
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Route custom host (required to set spec.host on Routes)
  - apiGroups:
      - route.openshift.io
    resources:
      - routes/custom-host
    verbs:
      - create
      - update

  # Networking
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - networkpolicies
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Resource quotas and limit ranges
  - apiGroups:
      - ""
    resources:
      - resourcequotas
      - limitranges
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Operators (OLM)
  - apiGroups:
      - operators.coreos.com
    resources:
      - subscriptions
      - operatorgroups
      - catalogsources
      - installplans
      - clusterserviceversions
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # OAuth (OpenShift)
  - apiGroups:
      - oauth.openshift.io
    resources:
      - oauthclients
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Config (OpenShift)
  - apiGroups:
      - config.openshift.io
    resources:
      - oauths
      - identities
    verbs:
      - get
      - list
      - watch
      - update
      - patch

  # Batch resources (for InstallPlan approver job)
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

---
# Bind the ClusterRole to ArgoCD's application controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-keycloak-manager
  labels:
    app.kubernetes.io/part-of: keycloak-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-keycloak-manager
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
