---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  channel: stable-1.18
  installPlanApproval: Automatic
  name: openshift-gitops
  source: redhat-operators
  sourceNamespace: openshift-marketplace
