---
# Example: Keycloak Operator with Pinned CSV Version
# This configuration pins the operator to a specific version and uses
# the InstallPlan approver for automated approval in GitOps workflows.

# Override values for infra/charts/keycloak-operator

namespace: keycloak

operator:
  name: rhbk-operator

  # Operator channel - determines available versions
  channel: stable-v26.2

  # Manual approval mode - prevents automatic upgrades
  # The InstallPlan approver job will handle approval
  installPlanApproval: Manual

  # Pin to specific CSV version
  # Update this value to upgrade the operator
  # Example versions: rhbk-operator.v26.2.0, rhbk-operator.v26.2.1
  startingCSV: "rhbk-operator.v26.2.0"

  # InstallPlan Approver - automates approval for GitOps
  installPlanApprover:
    enabled: true

    # Only approve if CSV matches startingCSV
    # Prevents unwanted upgrades when set to true
    enforceCSVMatch: true

    # Job timeout in seconds (10 minutes)
    timeout: 600

    # Number of retries if job fails
    backoffLimit: 3

    # Image for the approver job (oc CLI)
    image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

  # Optional: Use custom catalog source
  catalogSource:
    enabled: false
    name: custom-redhat-catalog
    image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
    tag: v4.20_2025_10_23

# How to use this file:
#
# 1. Deploy with pinned version:
#    helm upgrade --install keycloak-operator \
#      infra/charts/keycloak-operator \
#      -f infra/examples/pinned-operator-version.yaml
#
# 2. To upgrade the operator:
#    a. Update the startingCSV value above
#    b. Commit and push the change
#    c. ArgoCD will sync and the approver job will approve the new version
#
# 3. View approver job logs:
#    oc logs -n keycloak job/rhbk-operator-installplan-approver -f
#
# 4. Check InstallPlan status:
#    oc get installplan -n keycloak
#    oc describe installplan <name> -n keycloak
