---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-infra
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: keycloak-platform
    component: infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR-ORG/YOUR-REPO.git  # Update with your Git repository
    targetRevision: main
    path: argocd/infra/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
