---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-oauth
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rhpds/ocp-cluster-addons.git
    targetRevision: keycloak-wip
    path: argocd/charts/keycloak-oauth
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-config
  syncPolicy:
    automated:
      prune: false  # Don't auto-prune OAuth config
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: config.openshift.io
      kind: OAuth
      jsonPointers:
        - /spec/identityProviders
