---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-instance
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/rhpds/ocp-cluster-addons.git
    targetRevision: keycloak-wip
    path: keycloak/infra/charts/keycloak-instance
    helm:
      values: |
        namespace: keycloak
        deployer:
          domain: apps.cluster-lpx74.dyn.redhatworkshops.io
        keycloak:
          hostname: sso
          instances: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
