---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-oauth
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/rhpds/ocp-cluster-addons.git
    targetRevision: keycloak-wip
    path: keycloak/infra/charts/keycloak-oauth
    helm:
      values: |
        deployer:
          domain: apps.cluster-lpx74.dyn.redhatworkshops.io
        oauth:
          client:
            id: idp-4-ocp
            secret: oXr9i5JGJmAofpQf
          keycloak:
            hostname: sso
            realmName: sso
        rbac:
          clusterAdmin:
            enabled: true
            username: admin
          removeKubeadmin:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-config
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: config.openshift.io
      kind: OAuth
      jsonPointers:
        - /spec/identityProviders
