== Showroom Helm Chart for ArgoCD

This repository contains a Helm chart designed for deploying Showroom to Openshift ArgoCD.

=== Overview

When used with an ArgoCD Application, this Helm chart provides the following functionalities:

1. **Installs Showroom Chart from https://github.com/rhpds/showroom-deployer/**.

=== Use cases

. Dedicated single-tenant cluster
. Shared cluster with pre-provisioned users
. Shared cluster with on-demand tenants

Details of each use case:

. Dedicated single-tenant cluster
** Deploys a single Showroom pod in a single showroom namespace.
** Showroom config (see below)
** User data for showroom:
+
[,yaml]
----
user_data:
  # no `userN:` structure

  # whatever you send from AgV that needs to be in Showroom
  # use `agnosticd_passthrough_user_data` in AgV to pass through from child components to parent, if needed.
  # Look for copious examples in AgV
----
+
. Shared cluser with pre-provisioned users
** Deploys Showroom pods for each `userN`
** Users cannot access their own, nor others' showroom namespace and resources.
** Showroom config (see below)
** User data for showroom:
+
.User data
[,yaml]
----
user_data:
  # `userN:` structure is present

  # whatever you send from AgV that needs to be in Showroom
  # use `agnosticd_passthrough_user_data` in AgV to pass through from child components to parent, if needed.
  # Look for copious examples in AgV
----
+
. Shared cluster with on-demand tenants (aka "seat" or "TenantSandbox")
** Tenants have 1 or more users
** Tenants and their users cannot access their own, nor others' showroom namespace and resources.
** Deploys a single Showroom pod for each tenant user `showroom-{{ guid (aka tenant id)}}-{{ string or integer (aka user id) }}`
** Showroom config (see below)
** User data for showroom:
+
.Showroom config
[,yaml]
----
showroom_config:
  tenant_id: "{{ guid }}"

  ... see below for other defaults ...
----
+
.User data
[,yaml]
----
user_data:
  # `userN:` structure is present
----

Argo implementation:  `tenant_id` becomes name of Argo application.

== Usage

To use this Helm chart with ArgoCD, you can refer to the [application-showroom.yaml](application-showroom.yaml) file provided in this repository.

=== Prerequisites

- **ArgoCD**: Make sure you have ArgoCD installed and configured in your OpenShift cluster.

=== Reference Values for `showroom_config:` from showroom collection

[,yaml]
----
showroom_config:
  name: "showroom"
  namespace: "showroom-{{ guid | default('00000') }}"

  content_git_repo: https://github.com/rhpds/showroom_template_default.git
  content_git_repo_ref: main
  content_antora_playbook: default-site.yml
  content_image: quay.io/rhpds/showroom-content:v1.3.0

  terminal_type: showroom
  terminal_image: quay.io/rhpds/openshift-showroom-terminal-ocp:latest
  terminal_limits_cpu: 500m
  terminal_limits_memory: 1Gi
  terminal_requests_cpu: 50m
  terminal_requests_memory: 256Mi

  wetty_image: quay.io/rhpds/wetty:v2.5
  wetty_ssh_bastion_login: false

  chart_package_url: https://rhpds.github.io/showroom-deployer
  deployer_chart_name: showroom-single-pod
  deployer_chart_version: "^2.0.0"

  novnc_enable: false
  novnc_image: ghcr.io/rhpds/showroom-novnc:latest
  novnc_limits_cpu: 550m
  novnc_limits_memory: 256Mi
  novnc_requests_cpu: 50m
  novnc_requests_memory: 256Mi
  novnc_vnc_server_hostport: 128.0.0.1:5900
  novnc_vnc_server_password: password

  passthrough_user_data: false
  zero_touch_bundle: "https://github.com/rhpds/nookbag/releases/download/nookbag-v0.2.2/nookbag-v0.2.2.zip"
  zero_touch_ui_enabled: true

  # The service name to look for when waiting for the created route
  # Usually `showroom-proxy` for multi-pod deployment and `showroom` for single pod deployment
  service_name: "showroom"
----
