{{- $userList := list }}
{{- if eq .Values.users.mode "generate" }}
  {{- range $i := until (.Values.users.generate.count | int) }}
    {{- $userNum := add ($.Values.users.generate.startNumber | int) $i }}
    {{- $username := printf "%s%d-%s" $.Values.users.generate.prefix $userNum $.Values.deployer.guid }}
    {{- $userList = append $userList (dict "username" $username "firstName" (printf "%s%d" $.Values.users.firstName $userNum)) }}
  {{- end }}
{{- else if eq .Values.users.mode "explicit" }}
  {{- range $username := .Values.users.explicit.usernames }}
    {{- $fullUsername := $username }}
    {{- if $.Values.users.explicit.appendGuid }}
      {{- $fullUsername = printf "%s-%s" $username $.Values.deployer.guid }}
    {{- end }}
    {{- $userList = append $userList (dict "username" $fullUsername "firstName" $username) }}
  {{- end }}
{{- end }}
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: tenant-{{ .Values.deployer.guid }}
  namespace: {{ .Values.keycloak.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app.kubernetes.io/name: keycloak-realm
    app.kubernetes.io/component: tenant
    app.kubernetes.io/instance: {{ .Values.deployer.guid | quote }}
spec:
  keycloakCRName: keycloak
  realm:
    id: tenant-{{ .Values.deployer.guid }}
    realm: tenant-{{ .Values.deployer.guid }}
    enabled: true
    sslRequired: external
    registrationAllowed: false
    loginWithEmailAllowed: true
    duplicateEmailsAllowed: false
    roles:
      realm:
        {{- toYaml .Values.users.realmRoles | nindent 8 }}
{{- if $userList }}
    users:
      {{- range $user := $userList }}
      - username: {{ $user.username }}
        enabled: true
        emailVerified: {{ $.Values.users.emailVerified }}
        email: {{ $user.username }}@{{ $.Values.users.emailDomain }}
        firstName: {{ $user.firstName }}
        lastName: {{ $.Values.users.lastName }}
        credentials:
          - type: password
            value: {{ $.Values.users.password }}
            temporary: {{ $.Values.users.temporary }}
        {{- if $.Values.users.realmRoles }}
        realmRoles:
          {{- range $.Values.users.realmRoles }}
          - {{ .name }}
          {{- end }}
        {{- end }}
        {{- if $.Values.users.groups }}
        groups:
          {{- toYaml $.Values.users.groups | nindent 10 }}
        {{- end }}
      {{- end }}
{{- else }}
    users: []
{{- end }}
    groups: []
